export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  GET_PRODUCT_DETAIL_REQUEST: "GET_PRODUCT_DETAIL_REQUEST",
  GET_PRODUCT_DETAIL_FAILURE: "GET_PRODUCT_DETAIL_FAILURE",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  ENABLE_PRODUCT_REQUEST: "ENABLE_PRODUCT_REQUEST",
  ENABLE_PRODUCT_SUCCESS: "ENABLE_PRODUCT_SUCCESS",
  ENABLE_PRODUCT_FAILURE: "ENABLE_PRODUCT_FAILURE",
};

export const initialDataConstants = {
  GET_INITIALDATA_REQUEST: "GET_INITIALDATA_REQUEST",
  GET_INITIALDATA_FAILURE: "GET_INITIALDATA_FAILURE",
  GET_INITIALDATA_SUCCESS: "GET_INITIALDATA_SUCCESS",

  IMPORT_DATA_WITH_NEW_INDEX_REQUEST: "IMPORT_DATA_WITH_NEW_INDEX_REQUEST",
  IMPORT_DATA_WITH_NEW_INDEX_SUCCESS: "IMPORT_DATA_WITH_NEW_INDEX_SUCCESS",
  IMPORT_DATA_WITH_NEW_INDEX_FAILURE: "IMPORT_DATA_WITH_NEW_INDEX_FAILURE",
};
